### ISSUE TITLE
[Bug] game keeps crashing

### ISSUE THREAD

**Issue by LPZO** [AntiCope/orion#13]
### Describe the bug

The game keeps crashing every time I try to use it

### Steps to reproduce

```plaintext
1. put it in mods folder
2. press play
3. crash
...
```

### Operating System

Windows

### Orion Version

0.1

### Meteor Version

meteor-client-0.4.7

### Minecraft Version

1.18.1

### Other mods

```plaintext
fabric-api-0.46.1+1.18
```

**Comment by tympanicblock61** [comment]
happens to me to

**Comment by C10udburst** [comment]
send the crash log

**Comment by tympanicblock61** [comment]
ok
