### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Vbuuu** [AntiCope/orion#4]
No Release LOL

**Comment by StormyBytes** [comment]
It may have been my fault. I was deleting several useless tags a few days ago and may have by accident deleted the dev build release. Doing a void commit (2f0477738791c30dd83d3d4e2ac1eb80e92132f1) in an attempt to rebuild.

**Comment by Vbuuu** [comment]
Ahh okay np :)

**Comment by StormyBytes** [comment]
The build ran, except because this hasn't been updated to the latest dev build the workflow failed. I'll try to provide an older version build which works on the latest release.

**Comment by StormyBytes** [comment]
Alright I have uploaded a [temporary latest meteor release](https://github.com/AntiCope/orion/releases/tag/Meteor-Release).

**Comment by StormyBytes** [comment]
A 1.18 build has been released. This issue is closed for real now.
