### ISSUE TITLE
[Bug] Crash when cancelling the open skin file dialog

### ISSUE THREAD

**Issue by SIMULATAN** [AntiCope/orion#6]
### Describe the bug

When typing `.skin` into the chat and closing the GUI, the game crashes because the path to the file is null.

Might open a PR soon

### Steps to reproduce

```plaintext
1. Type `.skin`
2. Click "cancel" in the file picker GUI
```

### Operating System

Windows

### Orion Version

0.1 - newest (downloaded today)

### Meteor Version

0.4.7-1373

### Minecraft Version

1.18.1

**Comment by SIMULATAN** [comment]
nvm i'm stupid, somehow misread the mod name...

i need to get more sleep

**Comment by C10udburst** [comment]
yeah wrong repo lole

https://github.com/AntiCope/meteor-rejects <- this is the right one

**Comment by SIMULATAN** [comment]
Thanks lol, imma make one rn
